# set(CPACK_PACKAGE_VERSION_MAJOR "1")
# set(CPACK_PACKAGE_VERSION_MINOR "0")
# set(CPACK_PACKAGE_VERSION_PATCH "0")
# set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

# set(CPACK_GENERATOR "NSIS") # NSIS 或者 "ZIP" 或 "WIX"
# set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Molecular and Crystal Editor")
# set(CPACK_PACKAGE_VENDOR "Open source software.")
# set(CPACK_PACKAGE_URL "https://github.com/hungaier/qppcad")
# # set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/data/images/qpp.ico")
# SET(CPACK_PACKAGE_CONTACT "aaa@163.com")
# set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
# set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
# set(CPACK_PACKAGE_EXECUTABLES ${PROJECT_NAME} ${PROJECT_NAME})

# set(CPACK_NSIS_MENU_LINKS "./${PROJECT_NAME}.exe" "QppCAD")

# set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut '$DESKTOP/QppCAD.lnk' '$INSTDIR/${PROJECT_NAME}.exe'")
# set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
# set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/data/images/qpp.ico")
# set(CPACK_NSIS_MUI_HEADERIMAGE "${CMAKE_CURRENT_SOURCE_DIR}/data/images/qpp.ico")
# set(CPACK_NSIS_PACKAGE_NAME "QppCAD")
# set(CPACK_NSIS_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION})
# set(CPACK_NSIS_PACKAGE_VENDOR "Open source software")
# set(CPACK_NSIS_PACKAGE_DESCRIPTION "Molecular and Crystal Editor") 
# set(CPACK_NSIS_BRANDING_TEXT "Molecular and Crystal Editor")
# set(CPACK_NSISDISPLAY_NAME "QppCAD")

# # set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
# set(CPACK_ZIP_USE_SOURCE_PERMISSIONS ON)
# set(CPACK_NSIS_MODIFY_PATH "ON")

set(CPACK_GENERATOR "NSIS")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Molecular and Crystal Editor")
set(CPACK_PACKAGE_VENDOR "Open source software.")
set(CPACK_PACKAGE_URL "https://github.com/hungaier/qppcad")
set(CPACK_PACKAGE_CONTACT "aaa@163.com")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")

set(_ICON_PATH "${CMAKE_CURRENT_SOURCE_DIR}\\\\data\\\\images\\\\qpp128x128.ico")

set(LAUNCHER_EXE "QppCAD_Launcher.exe")

# 设置可执行文件和图标
set(CPACK_NSIS_EXECUTABLE_ICON
  ${LAUNCHER_EXE} ${_ICON_PATH}
)

# 设置 NSIS 显示名称
set(CPACK_NSIS_DISPLAY_NAME "QppCAD")

# 设置 NSIS 程序图标
set(CPACK_NSIS_MUI_UNIICON ${_ICON_PATH})
set(CPACK_NSIS_MUI_ICON ${_ICON_PATH})

# 设置 NSIS 安装程序头部图标
set(CPACK_NSIS_MUI_HEADERIMAGE ${_ICON_PATH})

# 设置 NSIS 菜单链接
set(CPACK_NSIS_MENU_LINKS ${LAUNCHER_EXE} "QppCAD")

set(CPACK_NSIS_INSTALLED_ICON_NAME "$INSTDIR\\\\qpp128x128.ico")

# 设置 NSIS 额外快捷方式
set(CPACK_NSIS_CREATE_ICONS_EXTRA
    "CreateShortCut '$DESKTOP\\\\QppCAD.lnk' '$INSTDIR\\\\${LAUNCHER_EXE}' '$INSTDIR\\\\qpp128x128.ico'")

set(CPACK_NSIS_DELETE_ICONS_EXTRA
  "Delete '$DESKTOP\\\\QppCAD.lnk'"
)

# 设置 NSIS 其他配置
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_MODIFY_PATH "ON")



# 设置 CPack 包版本
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")